%
% This is part of BLFSbookja package.
%
% This is a CTIE change file for the original XML source of the BLFSbook.
%
@x
  <!ENTITY gi-docgen-buildsize     "17 MB (with tests)">
  <!ENTITY gi-docgen-time          "less than 0.1 SBU (with tests)">
@y
  <!ENTITY gi-docgen-buildsize     "17 MB (with tests)">
  <!ENTITY gi-docgen-time          "less than 0.1 SBU (with tests)">
@z

@x
      <title>Introduction to Gi-DocGen Module</title>
@y
      <title>Introduction to Gi-DocGen Module</title>
@z

@x
        <application>Gi-DocGen</application> is a document generator for
        GObject-based libraries. GObject is the base type system of the GNOME
        project. GI-Docgen reuses the introspection data generated by
        GObject-based libraries to generate the API reference of these
        libraries, as well as other ancillary documentation.
@y
        <application>Gi-DocGen</application> is a document generator for
        GObject-based libraries. GObject is the base type system of the GNOME
        project. GI-Docgen reuses the introspection data generated by
        GObject-based libraries to generate the API reference of these
        libraries, as well as other ancillary documentation.
@z

@x
      <bridgehead renderas="sect4">Package Information</bridgehead>
@y
      <bridgehead renderas="sect4">Package Information</bridgehead>
@z

@x
            Download (HTTP): <ulink url="&gi-docgen-download-http;"/>
@y
            Download (HTTP): <ulink url="&gi-docgen-download-http;"/>
@z

@x
            Download (FTP): <ulink url="&gi-docgen-download-ftp;"/>
@y
            Download (FTP): <ulink url="&gi-docgen-download-ftp;"/>
@z

@x
            Download MD5 sum: &gi-docgen-md5sum;
@y
            Download MD5 sum: &gi-docgen-md5sum;
@z

@x
            Download size: &gi-docgen-size;
@y
            Download size: &gi-docgen-size;
@z

@x
            Estimated disk space required: &gi-docgen-buildsize;
@y
            Estimated disk space required: &gi-docgen-buildsize;
@z

@x
            Estimated build time: &gi-docgen-time;
@y
            Estimated build time: &gi-docgen-time;
@z

@x
      <bridgehead renderas="sect4">Gi-DocGen Dependencies</bridgehead>
@y
      <bridgehead renderas="sect4">Gi-DocGen Dependencies</bridgehead>
@z

@x
      <bridgehead renderas="sect5">Required</bridgehead>
      <para role="required">
        <xref linkend="markdown"/>,
        <xref linkend="packaging"/>,
        <xref linkend="pygments"/>,
        and <xref linkend="typogrify"/>
      </para>
@y
      <bridgehead renderas="sect5">Required</bridgehead>
      <para role="required">
        <xref linkend="markdown"/>,
        <xref linkend="packaging"/>,
        <xref linkend="pygments"/>,
        and <xref linkend="typogrify"/>
      </para>
@z

@x
      <bridgehead renderas="sect5">Optional</bridgehead>
      <para role="optional">
        <xref role='runtime' linkend='graphviz'/> (runtime, for visualizing
        class hierarchy graphs) and
        <xref linkend="pytest"/> (for testing)
      </para>
@y
      <bridgehead renderas="sect5">Optional</bridgehead>
      <para role="optional">
        <xref role='runtime' linkend='graphviz'/> (runtime, for visualizing
        class hierarchy graphs) and
        <xref linkend="pytest"/> (for testing)
      </para>
@z

@x
      <title>Installation of gi-docgen</title>
@y
      <title>Installation of gi-docgen</title>
@z

@x
    <para> Build the module: </para>
@y
    <para> Build the module: </para>
@z

@x
      Now, as the <systemitem class="username">root</systemitem> user:
@y
      Now, as the <systemitem class="username">root</systemitem> user:
@z

@x
      To test the installation, issue <command>pytest</command>.
@y
      To test the installation, issue <command>pytest</command>.
@z

@x
      <title>Contents</title>
@y
      <title>Contents</title>
@z

@x
        <segtitle>Installed Programs</segtitle>
        <segtitle>Installed Libraries</segtitle>
        <segtitle>Installed Directories</segtitle>
@y
        <segtitle>Installed Programs</segtitle>
        <segtitle>Installed Libraries</segtitle>
        <segtitle>Installed Directories</segtitle>
@z

@x
          <seg>gi-docgen</seg>
          <seg>None</seg>
          <seg>
            /usr/lib/python&python3-majorver;/site-packages/gidocgen and
            /usr/lib/python&python3-majorver;/site-packages/gi_docgen-&gi-docgen-version;.dist-info
          </seg>
@y
          <seg>gi-docgen</seg>
          <seg>None</seg>
          <seg>
            /usr/lib/python&python3-majorver;/site-packages/gidocgen and
            /usr/lib/python&python3-majorver;/site-packages/gi_docgen-&gi-docgen-version;.dist-info
          </seg>
@z

@x
        <bridgehead renderas="sect3">Short Descriptions</bridgehead>
@y
        <bridgehead renderas="sect3">Short Descriptions</bridgehead>
@z

@x gi-docgen
              manages documentation for libgobject based libraries.
@y
              manages documentation for libgobject based libraries.
@z
